name: SonarQube Analysis (Community)

on:
  pull_request:
    branches:
      - development
      - main

jobs:
  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=PRREVIEW \
            -Dsonar.host.url=http://192.168.1.229:9011/ \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.branch.name=${{ github.head_ref }}
