export const designation = [
  { key: "1", value: "Software Engineer" },
  { key: "2", value: "Tech Lead" },
  { key: "3", value: "Tech Manager " },
  { key: "4", value: "QA" },
  { key: "5", value: "R&D" },
  { key: "6", value: "QA Manager" },
  { key: "7", value: "Other" },
  { key: "8", value: "Sales Manager" },
  { key: "9", value: "Delivery Manager" },
  { key: "10", value: "BA" },
  { key: "11", value: "Principal Engineer" },
];
export const deparatment = [
  { key: "1", value: "R&D" },
  { key: "2", value: "Sales" },
  { key: "3", value: "QA" },
  { key: "4", value: "Acconts" },
  { key: "5", value: "IT" },
  { key: "6", value: "HR" },
  { key: "7", value: "Delivery" },
  { key: "8", value: "Finance" },
];
export const timeZones = [
  { key: "1", value: "Asia/Aden" },
  { key: "2", value: "Asia/Aqtobe" },
  { key: "3", value: "Asia/Jayapura" },
  { key: "4", value: "Asia/Vladivostok" },
  { key: "5", value: "Asia/Dushanbe" },
  { key: "6", value: "Asia/Hong_Kong" },
  { key: "7", value: "Asia/Aqtau" },
  { key: "8", value: "Asia/Pontianak" },
  { key: "9", value: "Asia/Kuching" },
  { key: "10", value: "Asia/Ulaanbaatar" },
  { key: "11", value: "Asia/Baghdad" },
  { key: "12", value: "Asia/Sakhalin" },
  { key: "13", value: "Asia/Chungking" },
  { key: "14", value: "Asia/Shanghai" },
  { key: "15", value: "Asia/Beirut" },
  { key: "16", value: "Asia/Yerevan" },
  { key: "17", value: "Asia/Kamchatka" },
  { key: "18", value: "Asia/Thimbu" },
  { key: "19", value: "Asia/Tel_Aviv" },
  { key: "20", value: "Asia/Hovd" },
  { key: "21", value: "Asia/Kashgar" },
  { key: "22", value: "Asia/Yakutsk" },
  { key: "23", value: "Asia/Damascus" },
  { key: "24", value: "Asia/Baku" },
  { key: "25", value: "Asia/Tehran" },
  { key: "26", value: "Asia/Oral" },
  { key: "27", value: "Asia/Taipei" },
  { key: "28", value: "Asia/Tashkent" },
  { key: "29", value: "Asia/Jakarta" },
  { key: "30", value: "Asia/Manila" },
  { key: "31", value: "Asia/Barnaul" },
  { key: "32", value: "Asia/Bangkok" },
  { key: "33", value: "Asia/Saigon" },
  { key: "34", value: "Asia/Samarkand" },
  { key: "35", value: "Asia/Yangon" },
  { key: "36", value: "Asia/Phnom_Penh" },
  { key: "37", value: "Asia/Katmandu" },
  { key: "38", value: "Asia/Ashkhabad" },
  { key: "39", value: "Asia/Qostanay" },
  { key: "40", value: "Asia/Almaty" },
  { key: "41", value: "Asia/Dubai" },
  { key: "42", value: "Asia/Tbilisi" },
  { key: "43", value: "Asia/Novosibirsk" },
  { key: "44", value: "Asia/Jerusalem" },
  { key: "45", value: "Asia/Makassar" },
  { key: "46", value: "Asia/Vientiane" },
  { key: "47", value: "Asia/Nicosia" },
  { key: "48", value: "Asia/Riyadh" },
  { key: "49", value: "Asia/Pyongyang" },
  { key: "50", value: "Asia/Ujung_Pandang" },
  { key: "51", value: "Asia/Karachi" },
  { key: "52", value: "Asia/Harbin" },
  { key: "53", value: "Asia/Gaza" },
  { key: "54", value: "Asia/Novokuznetsk" },
  { key: "55", value: "Asia/Atyrau" },
  { key: "56", value: "Asia/Khandyga" },
  { key: "57", value: "Asia/Kuala_Lumpur" },
  { key: "58", value: "Asia/Qyzylorda" },
  { key: "59", value: "Asia/Famagusta" },
  { key: "60", value: "Asia/Thimphu" },
  { key: "61", value: "Asia/Chita" },
  { key: "62", value: "Asia/Rangoon" },
  { key: "63", value: "Asia/Kuwait" },
  { key: "64", value: "Asia/Macao" },
  { key: "65", value: "Asia/Calcutta" },
  { key: "66", value: "Asia/Ho_Chi_Minh" },
  { key: "67", value: "Asia/Kabul" },
  { key: "68", value: "Asia/Tomsk" },
  { key: "69", value: "Asia/Macau" },
  { key: "70", value: "Asia/Krasnoyarsk" },
  { key: "71", value: "Asia/Kolkata" },
  { key: "72", value: "Asia/Qatar" },
  { key: "73", value: "Asia/Hebron" },
  { key: "74", value: "Asia/Dacca" },
  { key: "75", value: "Asia/Magadan" },
  { key: "76", value: "Asia/Ashgabat" },
  { key: "77", value: "Asia/Ust-Nera" },
  { key: "78", value: "Asia/Ulan_Bator" },
  { key: "79", value: "Asia/Srednekolymsk" },
  { key: "80", value: "Asia/Anadyr" },
  { key: "81", value: "Asia/Irkutsk" },
  { key: "82", value: "Asia/Muscat" },
  { key: "83", value: "Asia/Bahrain" },
  { key: "84", value: "Asia/Dili" },
  { key: "85", value: "Asia/Chongqing" },
  { key: "86", value: "Asia/Kathmandu" },
  { key: "87", value: "Asia/Seoul" },
  { key: "88", value: "Asia/Amman" },
  { key: "89", value: "Asia/Tokyo" },
  { key: "90", value: "Asia/Istanbul" },
  { key: "91", value: "Asia/Brunei" },
  { key: "92", value: "Asia/Choibalsan" },
  { key: "93", value: "Asia/Colombo" },
  { key: "94", value: "Asia/Omsk" },
  { key: "95", value: "Asia/Singapore" },
  { key: "96", value: "Asia/Dhaka" },
  { key: "97", value: "Asia/Urumqi" },
  { key: "98", value: "Asia/Yekaterinburg" },
  { key: "99", value: "Asia/Bishkek" },
];

export const Gender = [
  { key: "1", value: "Male" },
  { key: "2", value: "Female" },
  { key: "3", value: "Transgender" },
];
export const bloodGroup = [
  { key: "1", value: "O+" },
  { key: "2", value: "O-" },
  { key: "3", value: "A+" },
  { key: "4", value: "A-" },
  { key: "5", value: "B+" },
  { key: "6", value: "B-" },
  { key: "7", value: "AB+" },
  { key: "8", value: "AB-" },
];
export const domicile = [
  { key: "1", value: "India" },
  { key: "2", value: "USA" },
  { key: "3", value: "UAE" },
  { key: "4", value: "UK" },
  { key: "5", value: "Austraila" },
  { key: "6", value: "Canada" },
  { key: "7", value: "Russia" },
  { key: "8", value: "China" },
];
export const citizenship = [
  { key: "1", value: "India" },
  { key: "2", value: "USA" },
  { key: "3", value: "UAE" },
  { key: "4", value: "UK" },
  { key: "5", value: "Austraila" },
  { key: "6", value: "Canada" },
  { key: "7", value: "Russia" },
  { key: "8", value: "China" },
];
export const maritalStatus = [
  { key: "1", value: "Married" },
  { key: "2", value: "Unmarried" },
  { key: "3", value: "Divorced" },
  { key: "4", value: "Widow" },
];

export const ModuleOptions = [
  { key: "1", value: "Admistration" },
  { key: "2", value: "HRMS" },
  { key: "3", value: "Leave Management" },
  { key: "4", value: "Timesheet Management " },
  { key: "5", value: "Attendance Management" },
  { key: "6", value: "Performance Management" },
];

export const privileges = [
  { key: "1", value: "Employee" },
  { key: "2", value: "HR" },
  { key: "3", value: "System Admin" },
];

export const users = [
  { key: "1", value: "sysadmin" },
  { key: "2", value: "employee1" },
  { key: "3", value: "HRMANAGER" },
];

export const regionOptions = [
  { key: "1", value: "India-Karnataka" },
  { key: "2", value: "India-Telengana" },
  { key: "3", value: "United States" },
  { key: "4", value: "United Arab Emirates" },
  { key: "5", value: "United Kingdom" },
];
// export const empTypes = [
//   { key: "1", value: "Officers" },
//   { key: "2", value: "Workmen" },
//   { key: "3", value: "Technical" },
//   { key: "4", value: "Contract Labour" },
//   { key: "5", value: "Security" },
//   { key: "6", value: "Additional Security" },
// ];
export const empTypes = [
  { key: "1", value: "Intern" },
  { key: "2", value: "On Contract" },
  { key: "3", value: "On Probation" },
  { key: "4", value: "On Probation Period" },
  { key: "5", value: "Permanent" },
  { key: "6", value: "Probation" },
  { key: "7", value: "Default" },
];